### ISSUE TITLE
[CONTENT] How-tos and demos on creating NFTs on various chains

### ISSUE THREAD

**Issue by dchoi27** [protocol/nft-website#135]
Bucket issue tracking demos for beginners minting NFTs across various priority chains:

- [ ] Ethereum / EVM-compatible (port [Minty](https://docs.ipfs.io/how-to/mint-nfts-with-ipfs/#minty) over and clarify what EVM is + examples)
- [ ] Solana (via Metaplex SDK once integration there is done)
- [ ] Flow (have a metadata spec, but metadata kept on-chain)
- [ ] Tesos (spec: FA-2)
- [ ] Cardano (not sure if they have a spec (UTXO) - talk to Vuk)
- [ ] Polkadot

Comment on issue if you think we're missing any important chains!

**Comment by 113408** [comment]
Hey @dchoi27 any reason why BSC smart contracts are not in the list ?

**Comment by dchoi27** [comment]
Hey @113408 - I think that should be covered in a general EVM tutorial, but let me know if not.
