### ISSUE TITLE
[CONTENT] Tutorials for doing different things related to NFTs

### ISSUE THREAD

**Issue by dchoi27** [protocol/nft-website#138]
#135 will help give a breadth of examples (NFTs across chains in different ecosystems), but we will also cover tutorials (`tutorials`) giving depth to what you can do with NFTs. Net new content includes:

The default is to have tutorials use EVM-compatible contracts (as a sort of lingua franca, with the `smart-contract-examples` in #135 covering content across chains), but this doesn't have to be a strict requirement (e.g., @ jochasinga 's pet shop tutorial on Flow).

The current list:
- [ ] Building a Minting App (different than the `Designing a Minting App` page already in `/tutorials`)
- [ ] Building an NFT Marketplace, including a section around considerations at scale (especially for accessing content through an HTTP gateway) - this should be focused not on minting NFTs, but 
- [ ] Building a gallery app #42
- [ ] Using NFTs in games #26 
- [ ] Minting large NFTs / NFTs with a lot of files in a folder (https://github.com/ipfs-shipyard/nft.storage/issues/426#issuecomment-925443456) - lower prio
- [ ] Minting a thousands of NFTs at once (https://github.com/ipfs-shipyard/nft.storage/issues/426#issuecomment-925443456) - lower prio

If you have any suggestions on other tutorials on things you can do related to NFTs, please comment below.

**Comment by jochasinga** [comment]
- [x] Building a minting and marketplace app - Flow https://github.com/protocol/nft-website/issues/146
- [ ] Minting NFTs on Avalanche - TBC
