### ISSUE TITLE
Implement MVP branding

### ISSUE THREAD

**Issue by jessicaschilling** [protocol/nft-website#5]
Implement the basic branding necessary for MVP launch. Note that adding more of a splash-page-style homepage is happening post-MVP under #11.

## To do
- [x] Implement fonts, colors, overall styling
- [x] Once logo/wordmark finalized under https://github.com/protocol/design-shop/issues/586, update header _wordmark_ art (including optimizing SVG)
- [x] Once logo/wordmark finalized under https://github.com/protocol/design-shop/issues/586, update header _logo_ art (including optimizing SVG)
- [x] Once logo/wordmark finalized under https://github.com/protocol/design-shop/issues/586, update all favicon images (note: any existing ones in repo should be replaced even if they "look right" as colors and details will have changed slightly)
- [x] Once logo/wordmark finalized under https://github.com/protocol/design-shop/issues/586, update social card art (including the social card art in this repo's GitHub prefs)
- [x] Update welcome-page art once https://github.com/protocol/design-shop/issues/599 is done, including optimizing SVG
- [x] Update "under construction" art once https://github.com/protocol/design-shop/issues/600 is done, including optimizing SVG
- [ ] ~~If possible, modify [off-site link icon](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/core/lib/client/components/OutboundLink.vue) to match overall pixellated visual metaphor (@zebateira, can you please advise?)~~
- [x] If possible, modify ["back to top" arrow](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/plugin-back-to-top/BackToTop.vue) to match overall pixellated visual metaphor (@zebateira, can you please advise?)
- [x] Fix background colors on 404 pages
- [x] Check over CSS overall, including removing `!important` declarations whenever possible and possibly consolidating/relocating CSS; right now there are style rules both in `/docs/.vuepress/theme/styles` and in individual components in `/docs/.vuepress/theme/components` and `/docs/.vuepress/theme/global-components`
- [x] Test on multiple browsers and viewport widths for consistency
- [x] If time, add dark mode/light mode options (if not, split out into its own post-MVP issue)

**Comment by jessicaschilling** [comment]
@zebateira - updated the original comment on this issue with a checklist of outstanding items. It's not as bad as it looks - many are about updating art once we get final files from @ericronne's team - but I would definitely appreciate any work that you've got time for on these. 🙏  Please let me know how you'd prefer to divide/conquer!

**Comment by zebateira** [comment]
the "back-to-top" arrow we can override easily, but the outbound link I have to test it.

**Comment by jessicaschilling** [comment]
Dark theme isn't merged as of this moment, but it's in active review under https://github.com/protocol/nft-website/pull/71. Closing this issue to keep the board tidy as we lead up to soft launch 🎊
