### ISSUE TITLE
Launch cutover checklist

### ISSUE THREAD

**Issue by jessicaschilling** [protocol/nft-website#7]
This issue is a holding pen for pre-launch items to be worked shortly before or day of launch. Please amend this comment to add more. We can move to separate issues as needed when launch is closer.

- [x] Make repo public (and protect any branches necessary to make PRs cleaner)
- [x] Reconfigure repo perms to remove any unnecessary access
- [x] Set up DNS for domain name
- [x] Update public repo readme, URL, etc
- [x] Confirm Speedcurve is pulling in data
- [x] Confirm Countly metrics are pulling in production data
- [x] Confirm social cards include image (see https://github.com/protocol/nft-website/issues/18#issuecomment-846311221 )

**Comment by jessicaschilling** [comment]
Have a DNS request open with @andyschwab for pointing nftschool.dev 😊

**Comment by andyschwab** [comment]
🎉  https://nftschool.dev/

**Comment by jessicaschilling** [comment]
Tested social cards in Slack, iMessage, Twitter, Facebook.

**Comment by jessicaschilling** [comment]
Tested Countly, Speedcurve are relaying production data. Good to close this issue!
